CREATE TABLE IF NOT EXISTS Users (
    id SERIAL PRIMARY KEY NOT NULL,
    name VARCHAR(100) NOT NULL,
    oauth_id VARCHAR(200) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS Posts (
    id SERIAL PRIMARY KEY NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    title VARCHAR(200) NOT NULL,
    content TEXT NOT NULL,
    user_id INTEGER REFERENCES Users(id) NOT NULL
);

CREATE TABLE IF NOT EXISTS Comments (
    id SERIAL PRIMARY KEY NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    content TEXT NOT NULL,
    user_id INTEGER REFERENCES Users(id) NOT NULL,
    post_id INTEGER REFERENCES Posts(id) NOT NULL
);
