apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  POSTGRES_DB: dGVzdA==
  POSTGRES_HOST: bG9jYWxob3N0
  POSTGRES_USER: YWRtaW4=
  POSTGRES_PASSWORD: YWRtaW4=
  POSTGRES_PORT: NTQzMg==
  POSTGRES_MAX: MTA=
  DATABASE_URL: cG9zdGdyZXM6Ly9hZG1pbjphZG1pbkBkYXRhYmFzZS1zZXJ2aWNlOjU0MzIvdGVzdA==